language: php
php: ['7.1']
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/travis_phantomjs

addons:
#  firefox: '52.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - nginx
      - realpath
      - oracle-java8-set-default

before_script:
#  - echo $PATH
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
  - mkdir $HOME/bin
  - curl -L https://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar -o $HOME/bin/selenium.jar
#  chrome driver
  - curl -L http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip -o $HOME/bin/chromedriver_linux64.zip
  - unzip $HOME/bin/chromedriver_linux64.zip -d $HOME/bin/
#  geckodriver
#  - curl -L https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz -o   $HOME/bin/geckodriver-v0.17.0-linux64.tar.gz
#  - tar -xzf $HOME/bin/geckodriver-v0.17.0-linux64.tar.gz -C $HOME/bin
#  run selenium with chromedriver
  - java -Dwebdriver.gecko.driver=$HOME/bin/chromedriver -jar $HOME/bin/selenium.jar -log /tmp/webdriver.log > /tmp/webdriver_output.log 2>&1 &
#  run selenium with geckodriver
#  - java -Dwebdriver.gecko.driver=$HOME/bin/geckodriver -jar $HOME/bin/selenium.jar -log /tmp/webdriver.log > /tmp/webdriver_output.log 2>&1 &
  - sleep 3

install:
  - composer install
  - travis/install-nginx.sh
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:create
#  - bin/console server:start -p 8080

script:
#  - curl -vsf 'http://localhost:8080/app.php/admin/dashboard' &> /dev/stdout
  - bin/behat -p selenium2 -vvv
#  - bin/phpunit --coverage-clover=coverage.clover
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - cat /tmp/webdriver.log
  - cat /tmp/webdriver_output.log
