language: php
php: ['7.1']
sudo: false
dist: trusty

matrix:
  include:
  - php: 7.1
    env: TESTSUITE=behat
#  - php: 7.1
#    env: TESTSUITE=unit
#  - php: 7.1
#    env: TESTSUITE=functional
#  - php: 7.1
#    env: TESTSUITE=phpmd
  - php: 7.1
    env: TESTSUITE=phpcs
  - php: 7.1
    env: TESTSUITE=deprecation

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/travis_phantomjs

addons:
#  firefox: '52.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - nginx
      - realpath
      - oracle-java8-set-default

before_install:
  - mkdir $HOME/bin
  - ./.travis/$TESTSUITE.sh before_install;

install:
  - ./.travis/$TESTSUITE.sh install;

before_script:
  - ./.travis/$TESTSUITE.sh before_script;

script:
  - ./.travis/$TESTSUITE.sh script;

after_success:
  - ./.travis/$TESTSUITE.sh after_success;

after_failure:
  - ./.travis/$TESTSUITE.sh after_failure;

after_script:
  - ./.travis/$TESTSUITE.sh after_script;
