<?php

namespace AppBundle\Repository;

/**
 * ArtWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtWorkTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
