<?php

namespace AppBundle\Repository;

/**
 * ExhibitionTranslationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitionTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
