# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    admin.artwork:
            class: AppBundle\Admin\ArtWorkAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "ArtWork"
                  label: "ArtWork"
                  label_catalogue: "AppBundle"
            arguments:
                 - ~
                 - AppBundle\Entity\ArtWork
                 - ~
    admin.exhibition:
            class: AppBundle\Admin\ExhibitionAdmin
            tags:
                 - name: sonata.admin
                   manager_type: orm
                   group: "Exhibition"
                   label: "Exhibition"
                   label_catalogue: "Exhibition"
            arguments:
                 - ~
                 - AppBundle\Entity\Exhibition
                 - ~
    app.contains_slug_edit_validator:
            class: AppBundle\Validator\Constraints\SlugEditValidator
            arguments: ['@doctrine.orm.entity_manager']
            tags:
                - { name: validator.constraint_validator }
