# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    admin.artwork:
        class: AppBundle\Admin\ArtWorkAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "ArtWork"
              label: "ArtWork"
              label_catalogue: "AppBundle"
        arguments:
             - ~
             - AppBundle\Entity\ArtWork
             - ~
