# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    admin.artwork:
            class: AppBundle\Admin\ArtWorkAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "ArtWork"
                  label: "ArtWork"
                  label_catalogue: "AppBundle"
            arguments:
                 - ~
                 - AppBundle\Entity\ArtWork
                 - ~
    admin.exhibition:
            class: AppBundle\Admin\ExhibitionAdmin
            tags:
                 - name: sonata.admin
                   manager_type: orm
                   group: "Exhibition"
                   label: "Exhibition"
                   label_catalogue: "Exhibition"
            arguments:
                 - ~
                 - AppBundle\Entity\Exhibition
                 - ~
    admin.faqcategory:
            class: AppBundle\Admin\FAQCategoryAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "Category"
                  label: "Category"
                  label_catalogue: "Category"
            arguments:
                - ~
                - AppBundle\Entity\FAQCategory
                - ~
