Feature: Slug behavior
  In order to have semantic url in my gallery
  As an artist
  I what to have slug to every art work

  Background:
    Given I open "Art Work Create Page"

  Scenario: Autogenerated slug
    Given fill form with:
      | Title            | Sunset on koh Pan Gan           |
      | Creation date    | 15/05/2017                      |
      | Price            | 100500                          |
      | Materials        | canvas, acrylic                 |
      | Width            | 60                              |
      | Height           | 80                              |
    Then the "Slug" field should contain ""
    But I press "Create"
    Then the "Slug" field should contain "sunset-on-koh-pan-gan"

  @skip
  Scenario: Slug should not contain any special chapters
    Given I fill in "Title" with "Sunset $%^&)(*!@#\/ on koh Tao"
    When press "Create"
    Then the "Slug" field should contain "sunset-on-koh-tao"

  @skip
  Scenario: Slug value should be unique
    Given I fill in "Title" with "Self portrait"
    When press "Create"
    Then the "Slug" field should contain "self-portrait"
    But I open "Art Work Create Page"
    And fill in "Title" with "Self portrait"
    When press "Create"
    Then the "Slug" field should contain "self-portrait-1"
    And should see "Slug was autogenerated, please edit it before publish art work"

  @skip
  Scenario: Slug is editable until art work is publish
    Given I open "Art Work Create Page"
    And fill form with:
      | Title            | Sunset on koh Samui            |
      | Slug             | sunset-on-koh-samui            |
      | Is Published     | Unpublished                    |
    And press "Create"
    Then filed "Slug" should be editable
    But I fill in "Is Published" with "On front"
    And press "Create"
    Then field "Slug" should be not editable
    But I fill in "Is Published" with "Unpublished"
    And press "Create"
    Then field "Slug" should be not editable
